### ISSUE TITLE
Bolt writes "// existing code" when it updates code which breaks the website. 

### ISSUE THREAD

**Issue by mobm93** [stackblitz/bolt.new#471]
Once the project is a bit detailed and requires changes in few pages. Bolt writes the updated code snippet but does not write the old code instead writes  "//-- Existing code goes here" which pretty much breaks the website. 
It should either always write full code or just share the code snippet to be updated so we can just add it along existing code or overwrite where needed

**Comment by taengaaa** [comment]
Same issue here.

**Comment by taengaaa** [comment]
Example: 

```
// Rest of the code remains the same...

export default function ProductOverview() {
  // ... (rest of the component code)

  return (
    <div className="container mx-auto p-4">
      {/* ... (rest of the JSX) */}
```

**Comment by kc0tlh** [comment]
@mobm93 & @taengaaa thanks for the feedback! Tracking workarounds and the resolution in #124

**Comment by kc0tlh** [comment]
**🎉 FIX LANDED** we have shipped an update that should permanently resolve this issue! Please share examples if you are still experiencing this error after 1pm PST on October 22'nd.

**Comment by fyyying** [comment]
I noticed the same thing still, multiple times when it should update some code it would just make some comments: // Rest of the component implementation...

**Comment by kamal0808** [comment]
Still happening
Is there a workaround? Like adding "Always write complete code"

**Comment by HeyGetnet** [comment]
Was a fix issue for this? I still see this issue happening on bolt.new

**Comment by jason-digital** [comment]
No way this was fixed - it keeps omitting sections when I want it to create a new section. When I ask it to include all sections it will add the omitted section back but so much of the functionality/design would get lost. Even the copy changes. A very useful tool but super frustrating.

**Comment by lomar92** [comment]
Same here. The Fix is still not here and is burning my money.

**Comment by solverajake** [comment]
Adding the diff do not really help the code is fixed then right after at the last time bolt rewrite the entire file then stop at approx 825 lines of code please fix this issue i lost about 30 millions token trying to fix my code.

**Comment by PrimeLevo** [comment]
Bolt is really waste of money at this point, it writes the whole code all over again even when I'm just asking for a simple change and what's even worse is that it breaks the whole code all the time
